export const GET_WEDDING_COLLECTIONS = "GET_COLLECTIONS";
export const POST_WEDDING_COLLECTIONS = "POST_COLLECTIONS";

export const GET_BABYS_COLLECTIONS = "GET_BABYS_COLLECTIONS"
export const POST_BABYS_COLLECTIONS = "POST_BABYS_COLLECTIONS";

export const GET_BABY_SHOWER_COLLECTIONS = "GET_BABY_SHOWER_COLLECTIONS"