export const GET_BANNER = "GET_BANNER";
export const GET_BABYSHOOT = "GET_BABYSHOOT";
export const GET_BABYSHOWER = "GET_BABYsHOWER";
export const GET_PRODUCTSHOOT = "GET_PRODUCTSHOOT";
export const GET_RECENTSTORIES = "GET_RECENTSTORIES";
export const GET_WEDDING = "GET_WEDDING";
